backend:
  name: git-gateway
  branch: main

local_backend:
  url: http://localhost:8082/api/v1
  allowed_hosts: ["192.168.0.1"]
publish_mode: editorial_workflow

media_folder: static/img
public_folder: img
locale: "ko"

collections: # A list of collections the CMS should be able to edit
  - name: "setting"
    label: "Setting"
    slug: "Setting"
    delete: false # Prevent users from deleting documents in this collection
    public_folder: ""
    media_folder: ""
    files:
      - name: "general"
        label: "Site Settings"
        file: "contents/setting/setting.json"
        description: "General Site Settings"
        path: "setting"
        fields:
          - { label: "아파트 명", name: "apartment", widget: "string" }
          - label: "로고"
            name: "logo"
            widget: "object"
            fields:
              - {
                  label: "로고 이미지",
                  name: "logo_image",
                  widget: image,
                  required: true,
                  default: "/"
                }
              - {
                  label: "로고 설명",
                  name: logo_image_alt,
                  widget: string,
                  required: true,
                }
          - { label: "메뉴", name: "menu", widget: "list" }
  - name: "slider"
    label: "썸네일 이미지 슬라이더"
    slug: "slider"
    delete: false
    files:
      - name: "thumbnail"
        label: "썸네일 이미지"
        file: "contents/slider/index.mdx"
        description: "썸네일 이미지 슬라이더 이미지 추가"
        path: "contents/slider"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "slider" }
          - label: "이미지 리스트"
            name: "imageInfos"
            widget: "list"
            fields:
              - label: "이미지 정보"
                name: "imageInfo"
                widget: "object"
                fields:
                  - { label: "이미지", name: "image", widget: "image" }
                  - { label: "대체 텍스트", name: "alt", widget: "string" }
  - name: "footer"
    label: "Footer"
    files:
      - file: "contents/footer/footer.mdx"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "footer" }
          - {
              label: "전화번호",
              name: "phoneNumber",
              widget: "string",
            }
          - {
              label: "주소",
              name: "address",
              widget: "string",
            }
          - {
              label: "이미지",
              name: "footerImage",
              widget: "image",
            }
          - {
              label: "이미지 설명",
              name: "footerImageAlt",
              widget: "string",
            }
  - name: "category"
    label: "분양 정보"
    description: "사업 개요, 입지환경 등 페이지 추가"
    folder: "contents/category"
    slug: "{{title_en}}"
    path: "{{slug}}/index"
    extension: "mdx"
    format: "frontmatter"
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "category" }
      - { label: "제목(한글)", name: "title", widget: "string" }
      - label: "제목(영문)"
        name: "title_en"
        widget: "string"
        hint: >
          페이지 주소의 https:.../info/ 뒤에 사용될 값
          ex)
          사업개요 - overview |
          입지환경 - environment |
          상품안내 - production |
          프리미엄 - premium |
          관심고객등록 - register
      - { label: "정보", name: "info", widget: "category" }
