backend:
  name: git-gateway
  branch: main

local_backend:
  url: http://localhost:8083/api/v1
  allowed_hosts: ["192.168.0.1"]
publish_mode: editorial_workflow

media_folder: static/img
public_folder: img
locale: "ko"

collections: # A list of collections the CMS should be able to edit
  - name: "setting"
    label: "Setting"
    slug: "Setting"
    delete: false # Prevent users from deleting documents in this collection
    public_folder: ""
    media_folder: ""
    description: "General - 기본 세팅 - 아파트 명, 로고, 전화번호 등 | 질문지 - 관심고객등록 정보 입력"
    files:
      - name: "general"
        label: "Site Settings"
        file: "contents/setting/setting.json"
        path: "contents/setting"
        fields:
          - {
              label: "Type",
              name: "type",
              widget: "hidden",
              default: "setting",
            }
          - { label: "아파트 명", name: "apartment", widget: "string" }
          - {
              label: "짧은 설명",
              name: "short",
              widget: "string",
              hint: "썸네일에 사용할 짧은 소개. ex) 총 809세대 대단지 블록형 단독주택 | 1661-0426",
            }
          - label: "로고"
            name: "logo"
            widget: "object"
            fields:
              - {
                  label: "로고 이미지",
                  name: "image",
                  widget: "image",
                  required: true,
                }
              - {
                  label: "로고 설명",
                  name: "alt",
                  widget: "string",
                  required: true,
                }
              - {
                  label: "로고 이름",
                  name: "title",
                  widget: "string",
                  required: true,
                }
          - { label: "썸네일 이미지", name: "slider", widget: "images" }
          - { label: "회사명", name: "corporate", widget: "string" }
          - { label: "대표자", name: "name", widget: "string" }
          - { label: "사무실 주소", name: "address", widget: "string" }
          - { label: "이메일", name: "email", widget: "string" }
          - { label: "전화번호", name: "phoneNumber", widget: "string" }
          - {
              label: "키워드",
              name: "keywords",
              widget: "customList",
              hint: "쉼표로 구분, 키워드 리서치: https://ads.google.com/intl/ko_KR/home/",
            }
      - name: "question"
        label: "질문지"
        file: "contents/setting/question.json"
        path: "contents/setting"
        fields:
          - {
              label: "Type",
              name: "type",
              widget: "hidden",
              default: "questions",
            }
          - { label: "질문지", name: "questions", widget: "questions" }
          - label: "입력 정보"
            name: "info"
            widget: "list"
            hint: 입력받을 정보
            fields:
              - { label: "정보 명", name: "title", widget: string }
              - { label: "정보 명(영어)", name: "name", widget: string }
  - name: "category"
    label: "분양 정보"
    description: "사업 개요, 입지환경 등 페이지 추가"
    folder: "contents/category"
    slug: "{{title_en}}"
    path: "{{slug}}/index"
    extension: "mdx"
    format: "frontmatter"
    create: true
    summary: "{{priority}} - {{title}}"
    sortable_fields: ["priority"]
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "category",
        }
      - { label: "제목(한글)", name: "title", widget: "string" }
      - label: "제목(영문)"
        name: "title_en"
        widget: "string"
        hint: >
          페이지 주소의 https:.../info/ 뒤에 사용될 값
          ex)
          사업개요 - overview |
          입지환경 - environment |
          상품안내 - production |
          프리미엄 - premium |
          관심고객등록 - register
      - {
          label: "우선순위",
          name: "priority",
          widget: "number",
          value_type: "int",
          min: 1,
          max: 100,
          step: 1,
          default: 99,
        }
      - { label: "정보", name: "info", widget: "category" }
